scalar JSON

type Query {
  getCollaborators: [Collaborator]
  getCollaborator(collaboratorId: Int): [Collaborator]
  getFeedbackForCollaborator(collaboratorId: Int): [Feedback]
}

type Mutation {
  createFeedback(collaboratorId: Int, input: InputFeedback): Feedback
  incrementLikeForFeedback(collaboratorId: Int, feedbackId: Int, input: InputFeedback): Feedback
  deleteFeedback(collaboratorId: Int, feedbackId: Int, dateFeedback: String): Feedback
}

type Collaborator {
  id: Int
  createdAt: String
  name: String
  avatar: String
  company: String
  role: String
}   

type Feedback {
  id: Int
  collaboratorId: Int
  createdAt: String
  message: String
  like: Int
}

input InputFeedback {
  collaboratorId: Int
  message: String
  like: Int
}